#!/usr/bin/env zsh

curdir=$PWD
[[ -e .last_multi_watched ]] && {
    "Kill old processes"
    kill $(<.last_multi_watched)
}
serverpid=""
if which mighty >/dev/null; then
    cd _site && \
    mighty +RTS -N >/dev/null 2>&1 &
    serverpid=$!
elif which http-server; then
    cd _site && \
    http-server >/dev/null 2>&1 &
    serverpid=$!
else
    print -P -- "%BWARNING%b: Please serve _site/ directory with an HTTP Server"
    print -P -- "%BWARNING%b: You might install http-server or mighty for example"
    print
fi
cd $curdir

# sass
sass -I . --watch Scratch/css:_site/Scratch/css &
sasspid=$!

checkfile=".last_multi_watched"

ONCE=0
[[ $1 = "once" ]] && { ONCE=1 }

error(){print -- $* >&2; exit 1}

((ONCE == 0)) && \
[[ -e $checkfile ]] && \
{
currenttime=$(date +"%s")
case $(uname) in
    Darwin) checkfilemodifiedtime=$(stat -f %m $checkfile);;
    Linux) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
    *) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
esac
(( $currenttime - $checkfilemodifiedtime  < 5)) && error "watching in progress (wait at least 5 seconds if you killed it)"
}

echo $serverpid $sasspid > .last_multi_watched

while true; do
  ./update-from-multi
  ((ONCE == 1)) && break
  touch $checkfile
  sleep 2
done

