#!/usr/bin/env zsh

compileAndPreview(){
    print -- "Compiling and building"
    cabal-dev install && \
    ./site clean && \
    while true; do ./site preview; done
}

./watch-multi & compileAndPreview
