#!/usr/bin/env zsh

error(){print -- $* >&2; exit 1}
curdir=$PWD
checkfile=".last_multi_watched"

cd $curdir

ONCE=0
for functionality in $@; do
    case $functionality in
        -h|--help|help)
            print -- "Usage: ${0:t} [command ...]"
            print -- "where command can be:"
            print -- "css\tWatch and update sass files"
            print -- "once\tOnly build once"
            exit 0
            ;;
        css) # sass
            cd content
            sass -I . --watch Scratch/css:_site/Scratch/css &
            cd $curdir
            ;;
        once) ONCE=1 ;;
    esac
done

((ONCE == 0)) && \
[[ -e $checkfile ]] && \
{
currenttime=$(date +"%s")
case $(uname) in
    Darwin) checkfilemodifiedtime=$(stat -f %m $checkfile);;
    Linux) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
    *) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
esac
(( $currenttime - $checkfilemodifiedtime  < 5)) && \
    error "watching in progress (wait at least 5 seconds if you killed it)"
}

cd content
stack exec yblog watch &

cd ..
while true; do
  ./tools/update-from-multi
  ((ONCE == 1)) && break
  touch $checkfile
  sleep 2
done

