#!/usr/bin/env zsh

curdir=$PWD
[[ -e .last_multi_watched ]] && {
    "Kill old processes"
    kill $(<.last_multi_watched)
}

cd $curdir

ONCE=0
for functionality in $@; do
    case $functionality in
        css) # sass
            sass -I . --watch Scratch/css:_site/Scratch/css &
            sasspid=$!
            ;;
        once) ONCE=1 ;;
    esac
done

checkfile=".last_multi_watched"

error(){print -- $* >&2; exit 1}

((ONCE == 0)) && \
[[ -e $checkfile ]] && \
{
currenttime=$(date +"%s")
case $(uname) in
    Darwin) checkfilemodifiedtime=$(stat -f %m $checkfile);;
    Linux) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
    *) checkfilemodifiedtime=$(stat --printf %Y $checkfile);;
esac
(( $currenttime - $checkfilemodifiedtime  < 5)) && error "watching in progress (wait at least 5 seconds if you killed it)"
}

echo $serverpid $sasspid > .last_multi_watched

cd content
stack exec yblog watch &

cd ..
while true; do
  ./tools/update-from-multi
  ((ONCE == 1)) && break
  touch $checkfile
  sleep 2
done

